version: '3.8'

services:
  parking_db:
    container_name: parking_db
    platform: linux/x86_64
    build: ./database
    volumes:
      - ./database/db:/docker-entrypoint-initdb.d
      - ./database/conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3306"
    env_file:
      - ./database/local.env
    # pseudo terminal
    tty: true

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8077:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=parking_db

  server:
    container_name: server
    platform: linux/x86_64
    build: ./backend/server
    ports:
      - "8080:80"
    env_file:
      - ./backend/server/local.env
    depends_on:
      - parking_db
    tty: true